# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mvcsite:
    image: mvcsite
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: red_alien
    command: --init-file /InitMariaDB.sql
